### ISSUE TITLE
Deob 没找到字符串数组 +0ms

### ISSUE THREAD

**Issue by wangsen2020** [kuizuo/js-deobfuscator#11]
总是
[tmp.zip](https://github.com/kuizuo/js-deobfuscator/files/15316610/tmp.zip)
运行：npx deob tmp/FileStorage.js -o tmp
提示这个
Deob 没找到字符串数组 +0ms
Deob 没找到解密器 +2ms
Deob 解密结果: Map(0) {} +1ms

好像很多都没识别出来，我发现一个网站处理的很好，你可以参考一下看看：
https://dev-coco.github.io/Online-Tools/JavaScript-Deobfuscator.html
我对这个项目很感兴趣！微信18976917166

**Comment by kuizuo** [comment]
那个文件内容太小了，导致数组长度太少了，按如下配置文件再次执行便可。

![image](https://github.com/kuizuo/js-deobfuscator/assets/61005888/2f51aaf4-3834-43c4-b97c-7e48b8fcc4a4)
