### ISSUE TITLE
为啥这种混淆还原不出来呢。

### ISSUE THREAD

**Issue by Lockey-J** [kuizuo/js-deobfuscator#6]
https://storage.360buyimg.com/jsresource/jcap/js/captcha_mobile_2024_01_08.min.js像这种。自执行类型的，然后是字典性质的。

**Comment by kuizuo** [comment]
有没有一种可能，这并不是一个混淆过的代码，而是一个 webpack 打包，并将代码压缩的代码。

如果你需要解包，或许你可以看看这个项目 [webcrack](https://webcrack.netlify.app/)
